# Generated by Django 5.1.4 on 2025-05-08 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invetoryapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
