# Generated by Django 5.1.4 on 2025-05-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetoryapp', '0004_product_supplier_alter_product_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('proname', models.CharField(default=None, max_length=100)),
                ('contact', models.CharField(max_length=15)),
            ],
        ),
    ]
