# Generated by Django 5.1.4 on 2025-05-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetoryapp', '0005_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cp', models.CharField(default=None, max_length=100)),
                ('sp', models.CharField(default=None, max_length=100)),
                ('quantity', models.CharField(max_length=15)),
            ],
        ),
    ]
