# Generated by Django 5.1.4 on 2025-05-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetoryapp', '0006_sales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stock', models.CharField(default=None, max_length=100)),
                ('PurchesList', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
