# Generated by Django 5.1.4 on 2025-05-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invetoryapp', '0009_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
