# Generated by Django 5.1.4 on 2025-05-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invetoryapp', '0010_alter_sales_id_alter_supplier_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Suppliers',
        ),
    ]
