# Generated by Django 5.1.4 on 2025-05-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invetoryapp', '0011_rename_supplier_suppliers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
    ]
